version: '3.8'

services:
    movies_database:
        container_name: movies_database
        image: mongo
        restart: always
        volumes:
            - "./data/db:/data/db"
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_DATABASE: movies
        ports:
            - "4850:27017"
          
    movies_api:
        container_name: movies_api
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env_prod
        ports:
            - "3000:3000"
        environment:
            WAIT_HOSTS_TIMEOUT: 60
            WAIT_HOSTS: "movies_database:4850"
    
networks:
  movies_network: